spring:
  application:
    name: apostas
  profiles:
    active: local

  config:
    import: optional:file:.env[.properties]

  jackson:
    time-zone: Europe/Lisbon

server:
  port: 8000

app:
  jwt:
    secret: ${JWT_SECRET}
    expiration-seconds: ${JWT_DURATION_SECONDS}

management:
  endpoints:
    web:
  endpoint:
    health:
      show-details: when-authorized
    secret: ${JWT_SECRET}
    expiration-seconds: 36000
  level:
    com.joker.apostas: INFO

